# LL2
LncLocator2    
Cell line H1   
Filter train ? Yes, i.e. exclude middle     
Fiter test ? No, i.e. inverse filter and keep middle       
Epochs = default = 100.     


In [8]:
try:
    from google.colab import drive
    IN_COLAB = True
    print('Running on CoLab')
    DRIVE_PATH='/content/drive/'
    drive.mount(DRIVE_PATH)
    DATA_PATH='drive/MyDrive/data/Localization/lncLocator2/'  # must end in "/"
except:
    IN_COLAB = False
    print('Running at home')
    DATA_PATH="./"
print('DATA PATH', DATA_PATH)

Running on CoLab
Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
DATA PATH drive/MyDrive/data/Localization/lncLocator2/


In [9]:
import sys
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
    print('GPU device not found')
else:
    print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [10]:
%pip install tensorboardX

In [11]:
import os
os.listdir()
%cd $DATA_PATH
os.listdir()

[Errno 2] No such file or directory: 'drive/MyDrive/data/Localization/lncLocator2/'
/content/drive/MyDrive/data/Localization/lncLocator2


['train.py',
 'dataset.py.Mar28',
 'record.py',
 'README.md',
 'model',
 'glove',
 '__pycache__',
 'checkpoints',
 '.ipynb_checkpoints',
 'config.py.Mar28',
 'CNRCI',
 'utils.py',
 'record.csv',
 'acc.png',
 'loss.png',
 'auroc.png',
 'main.py.Mar28',
 'config.py',
 'dataset.py',
 'main.py',
 'train.log']

In [17]:
import tensorboardX
!python main.py \
--train_dataset 'CNRCI/CNRCI_train_data_source/transcripts_type/H1.hESC/lncRNA.csv' \
--dev_dataset   'CNRCI/CNRCI_dev_data_source/transcripts_type/H1.hESC/lncRNA.csv' \
--test_dataset  'CNRCI/CNRCI_test_data_source/transcripts_type/H1.hESC/lncRNA.csv' \
--filter_train 'Y' \
--filter_dev 'N' \
--filter_test 'N' \
--device 'cuda'




Streaming output truncated to the last 5000 lines.
3200/9282 
loss: tensor(2.2689, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor([-1.3425,  1.0841, -1.2267, -1.1069, -1.9386, -1.8882, -1.8804,  1.6172,
        -1.2700, -2.5523, -1.7923,  1.6848, -1.0238,  1.3683, -1.6888, -1.6938,
         1.3041,  1.5850, -1.5794,  2.5384, -1.1375, -1.1923,  1.4382, -1.5850,
        -1.0486, -2.0000, -3.6897,  1.0555, -1.1699, -2.4594, -1.1737, -1.9875],
       device='cuda:0')
tensor([-1.4159,  0.3943, -1.3270,  1.2240,  1.3952, -1.5834, -1.0736,  1.6751,
        -1.9847, -1.6042, -1.6233,  1.0424, -1.2431,  1.6487, -0.8903, -1.4897,
         0.1547, -0.4859, -1.2363,  0.0609,  2.2204, -1.6702,  1.6649, -0.4950,
        -1.6523,  1.0993, -1.5640, -0.0337, -0.5059, -0.0438, -0.1691, -1.1821],
       device='cuda:0', grad_fn=<SqueezeBackward0>)
4800/9282 
loss: tensor(3.9146, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor([ 2.8826, -2.0937, -1.1676,  1.335

## Excution notes
This ran for about an hour on CoLab using a V100 GPU. The virtual machine reporting problems saving and we did not recover the train.log file. We did, however, recover and save the record.csv file, which captures the numerical portion of the log.