# LL2_H1_YY
The lncLocator2 publication highlights cell line H1.hESC. We used the same cell line for a test of performance on two test sets. This experiment exploited existing lncLocator2 code that made the middle-exclusion filter optional, with minor code changes to make it command-line settable. In the first set, with H1.hESC CNRCI values outside the \[-1,+1\] range, we saw AUROC 0.8282 and 75% accuracy on the test set. See also the log file.

This notebook invokes LncLocator2 code.
The data is for cell line H1.hESC.
The "YY" refers to the middle exclusion filtering: Yes on training set, Yes on test set.
Epochs = default = 100. 

In [11]:
try:
    from google.colab import drive
    IN_COLAB = True
    print('Running on CoLab')
    DRIVE_PATH='/content/drive/'
    drive.mount(DRIVE_PATH)
    DATA_PATH='drive/MyDrive/data/Localization/lncLocator2/'  # must end in "/"
except:
    IN_COLAB = False
    print('Running at home')
    DATA_PATH="./"
print('DATA PATH', DATA_PATH)

Running on CoLab
Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
DATA PATH drive/MyDrive/data/Localization/lncLocator2/


In [12]:
%pip install tensorboardX

In [13]:
import os
os.listdir()
%cd $DATA_PATH
os.listdir()

[Errno 2] No such file or directory: 'drive/MyDrive/data/Localization/lncLocator2/'
/content/drive/MyDrive/data/Localization/lncLocator2


['train.py',
 'dataset.py',
 'utils.py',
 'record.py',
 'README.md',
 'model',
 'glove',
 'CNRCI',
 '__pycache__',
 'checkpoints',
 'main.py',
 '.ipynb_checkpoints',
 'config.py',
 'loss.png',
 'record.csv',
 'acc.png',
 'auroc.png',
 'train.log']

## Run lncLocator2
The next cell launches the lncLocator2 main program.
The string parameters indicate lncLocator2 files containing H1.hESC lncRNA data.
The Y/N parameters indicate whether to apply the middle exclusion filter.

In [14]:
import tensorboardX
!python main.py \
--train_dataset 'CNRCI/CNRCI_train_data_source/transcripts_type/H1.hESC/lncRNA.csv' \
--dev_dataset   'CNRCI/CNRCI_dev_data_source/transcripts_type/H1.hESC/lncRNA.csv' \
--test_dataset  'CNRCI/CNRCI_test_data_source/transcripts_type/H1.hESC/lncRNA.csv' \
--filter_train 'Y' \
--filter_dev 'Y' \
--filter_test 'Y'





Streaming output truncated to the last 5000 lines.
       device='cuda:0')
tensor([-0.6817,  0.7429, -0.9148, -1.6916, -1.2929,  1.7716,  0.0135,  1.3940,
        -0.1089,  2.0475, -1.3702, -1.6855, -0.6617, -2.2666, -2.2207, -2.1086,
         0.4919, -1.6094,  0.3371, -0.7433,  1.4462, -1.8610, -0.9378, -0.5196,
        -1.1636,  0.0311,  0.5328, -1.9087, -1.4598,  1.3666, -2.0852, -1.6632],
       device='cuda:0', grad_fn=<SqueezeBackward0>)
4800/9282 
loss: tensor(2.1455, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor([-1.1726,  1.5075, -1.8182, -1.3857,  1.1690,  1.8711,  1.4418, -1.3425,
        -1.7814, -3.3709, -1.3655,  1.8192, -1.4400, -2.0368,  1.9240, -1.1478,
         1.3986,  3.6781,  1.4594,  1.4099, -1.6700, -1.5376, -1.9778, -2.3380,
         1.2110,  1.2538, -2.6245, -1.3530, -1.0480, -1.1822, -1.8458, -3.5607],
       device='cuda:0')
tensor([-1.4706,  1.0851, -2.6251, -1.5111,  1.3879, -1.7234,  0.6153, -2.1677,
        -1.5590, -1.6856, -0.828

## Excution notes
See the output log file.